from typing import Any

from fastapi import APIRouter, Request

from app.core.database import Base
from app.engineering.source_scanner import SourceScanner

router = APIRouter(
    prefix="/engineering",
    tags=["Engineering Context"],
)


@router.get("/openapi")
def get_openapi_spec(
request: Request,
) -> dict[str, Any]:
    """
    Returns the full OpenAPI specification generated by FastAPI.

    Useful for:
    - API contract discovery
    - Request/response schema discovery
    - Endpoint analysis
    - API impact analysis
    """

    return request.app.openapi()

@router.get("/endpoints")
def list_endpoints(
    request: Request,
    ) -> list[dict[str, Any]]:
    """
    Returns all registered API endpoints.
    """

    openapi = request.app.openapi()

    endpoints = []

    for path, methods in openapi.get("paths", {}).items():

        endpoints.append(
            {
                "path": path,
                "methods": [
                    method.upper()
                    for method in methods.keys()
                ],
            }
        )

    return endpoints

@router.get("/endpoints/search")
def search_endpoints(
    keyword: str,
    request: Request,
) -> list[dict[str, Any]]:
    """
    Search registered API endpoints by keyword.

    Example:
    /engineering/endpoints/search?keyword=product
    """

    openapi = request.app.openapi()

    keyword = keyword.lower().strip()

    if not keyword:
        return []

    results = []

    for path, methods in openapi.get("paths", {}).items():

        if keyword in path.lower():

            results.append(
                {
                    "path": path,
                    "methods": [
                        method.upper()
                        for method in methods.keys()
                    ],
                }
            )

    return results

@router.get("/endpoints/details")
def get_endpoint_details(
path: str,
request: Request,
) -> dict[str, Any]:
    """
    Returns the complete OpenAPI definition for a specific path.

    ```
    Example:
    /engineering/endpoints/details?path=/products
    """

    openapi = request.app.openapi()

    return openapi.get(
        "paths",
        {},
    ).get(
        path,
        {
            "message": f"Path '{path}' not found",
        },
    )
    

@router.get("/entities")
def get_database_entities() -> list[dict[str, Any]]:
    """
    Returns database tables registered in SQLAlchemy metadata.

    ```
    Includes basic table and column information.
    """

    entities = []

    for table in Base.metadata.tables.values():

        entities.append(
            {
                "name": table.name,
                "columns": [
                    column.name
                    for column in table.columns
                ],
            }
        )

    return entities


@router.get("/entities/details")
def get_entity_details(
table_name: str,
) -> dict[str, Any]:
    """
    Returns detailed information about a database table.
    """
    table = Base.metadata.tables.get(
        table_name,
    )

    if not table:
        return {
            "message": f"Table '{table_name}' not found",
        }

    return {
        "table": table_name,
        "columns": [
            {
                "name": column.name,
                "type": str(column.type),
                "nullable": column.nullable,
                "primary_key": column.primary_key,
                "default": (
                    str(column.default)
                    if column.default
                    else None
                ),
            }
            for column in table.columns
        ],
    }


@router.get("/models")
def get_pydantic_models(
request: Request,
) -> list[dict[str, Any]]:
    """
    Returns request/response Pydantic models used by FastAPI.

    ```
    Models are extracted from the generated OpenAPI specification.

    This endpoint represents API schemas rather than SQLAlchemy
    database models.
    """

    openapi = request.app.openapi()

    schemas = (
        openapi
        .get("components", {})
        .get("schemas", {})
    )

    models = []

    for name, schema in schemas.items():

        models.append(
            {
                "name": name,
                "schema": schema,
            }
        )

    return models


@router.get("/business-logic")
def get_business_logic(
    keywords: str | None = None,
) -> list[dict[str, Any]]:

    parsed_keywords = _parse_keywords(
        keywords
    )

    scanner = SourceScanner()

    results = scanner.search(
        parsed_keywords
    )

    return [
        {
            "component": item["name"],
            "file": item["file"],
            "type": item["type"],
            "line": item["line"],
            "keywords": item["keywords"],
            "change": (
                "Business logic may be affected because "
                f"{item['type']} '{item['name']}' "
                "references relevant requirement concepts."
            ),
        }
        for item in results
    ]

@router.get("/repositories")
def get_repositories(
keywords: str | None = None,
) -> list[dict[str, Any]]:
    """
    Returns repository/data-access context relevant to the supplied keywords.

    ```
    NOTE:
    This endpoint is currently a placeholder until source-code indexing
    or repository scanning is implemented.
    """

    _ = _parse_keywords(keywords)

    return []


@router.get("/integrations")
def get_integrations(
keywords: str | None = None,
) -> list[dict[str, Any]]:
    """
    Returns external integration context relevant to the supplied keywords.

    NOTE:
    This endpoint is currently a placeholder until source-code indexing
    or repository scanning is implemented.
    """

    _ = _parse_keywords(keywords)

    return []


@router.get("/documentation")
def get_documentation(
keywords: str | None = None,
) -> list[dict[str, Any]]:
    """
    Returns engineering documentation relevant to the supplied keywords.

    NOTE:
    This endpoint is currently a placeholder until documentation
    retrieval/search is implemented.
    """

    _ = _parse_keywords(keywords)

    return []


def _parse_keywords(
keywords: str | None,
) -> list[str]:

    if not keywords:
        return []

    return [
        keyword.strip().lower()
        for keyword in keywords.split(",")
        if keyword.strip()
    ]

@router.get("/components")
def get_components(
    keywords: str | None = None,
) -> list[dict[str, Any]]:
    """
    Returns application component context relevant to the supplied keywords.

    Scans the source tree for classes and functions that reference
    the supplied domain keywords.
    """

    parsed_keywords = _parse_keywords(keywords)

    scanner = SourceScanner()

    results = scanner.search(parsed_keywords)

    return [
        {
            "component": item["name"],
            "file": item["file"],
            "type": item["type"],
            "line": item["line"],
            "keywords": item["keywords"],
        }
        for item in results
    ]