from fastapi import APIRouter, Request
from sqlalchemy import inspect

from app.core.database import engine
from app.core.database import Base

router = APIRouter(
    prefix="/engineering",
    tags=["Engineering Context"]
)


@router.get("/openapi")
def get_openapi_spec(request: Request):
    """
    Returns the full OpenAPI specification generated by FastAPI.
    Useful for impact analysis and API contract discovery.
    """
    return request.app.openapi()


@router.get("/endpoints")
def list_endpoints(request: Request):
    """
    Returns all registered API endpoints.
    """

    openapi = request.app.openapi()

    endpoints = []

    for path, methods in openapi["paths"].items():
        endpoints.append(
            {
                "path": path,
                "methods": list(methods.keys())
            }
        )

    return endpoints


@router.get("/endpoints/search")
def search_endpoints(
    keyword: str,
    request: Request
):
    """
    Search endpoints by keyword.
    Example:
    /engineering/endpoints/search?keyword=product
    """

    openapi = request.app.openapi()

    results = []

    for path, methods in openapi["paths"].items():

        if keyword.lower() in path.lower():

            results.append(
                {
                    "path": path,
                    "methods": list(methods.keys())
                }
            )

    return results


@router.get("/endpoints/details")
def get_endpoint_details(
    path: str,
    request: Request
):
    """
    Get complete OpenAPI definition for a path.

    Example:
    /engineering/endpoints/details?path=/products
    """

    openapi = request.app.openapi()

    return openapi["paths"].get(
        path,
        {"message": f"Path '{path}' not found"}
    )


@router.get("/entities")
def get_database_entities():
    entities = []

    for table in Base.metadata.tables.values():
        entities.append(
            {
                "name": table.name,
                "columns": [column.name for column in table.columns]
            }
        )

    return entities


@router.get("/entities/details")
def get_entity_details(table_name: str):

    table = Base.metadata.tables.get(table_name)

    if not table:
        return {"message": "table not found"}

    return {
        "table": table_name,
        "columns": [
            {
                "name": column.name,
                "type": str(column.type),
                "nullable": column.nullable,
            }
            for column in table.columns
        ]
    }


@router.get("/models")
def get_sqlalchemy_models():
    """
    Returns SQLAlchemy model names registered
    in Base metadata.
    """

    models = []

    for table in Base.metadata.tables.values():
        models.append(
            {
                "name": table.name,
                "columns": [column.name for column in table.columns]
            }
        )

    return models